auto_dict/urls.py
from django.conf.urls import url
from . import views


app_name = 'auto_dict'

urlpatterns = [
    url(r'^tables', views.tables, name='tables'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^login/$', views.UserLoginView.as_view(), name="login"),
    url(r'^word_search/make_anki', views.make_anki_text, name='make_anki_text'),
    url(r'^word_search/', views.word_search, name='word_search'),
    url(r'^textfile_word_search/', views.textfile_word_search, name='textfile_word_search'),
    url(r'^$', views.school_class_dashboard, name="index"),
    url(r'^exam/(?P<exam_id>[0-9]+)/(?P<turn_in>[-\w]+)/$', views.exam, name="exam"),
    url(r'^exam/(?P<exam_id>[0-9]+)/', views.exam, name="exam"),
    url(r'^class/(?P<school_class_id>[0-9]+)/', views.school_class_dashboard, name="school_class_dashboard"),
    url(r'^turn_in_exam/(?P<exam_paper_id>[0-9]+)/$', views.turn_in_exam, name="turn_in_exam"),
    # url(r'^exam/(?P<exam_id>[0-9]+)/save_answer/$', views.save_answer, name="save_answer"),
    url(r'^save_answer/$', views.save_answer, name="save_answer"),
    url(r'^logout/$', views.user_logout, name="logout"),
    url(r'^change_user_image/$', views.change_user_image, name='change_user_image'),
    url(r'create_post/(?P<school_class_id>[0-9]+)/$', views.PostCreate.as_view(), name='create_post'),
    # url(r'^video/(?P<pk>[0-9]+)/$',
    #     views.VideoDetailView.as_view(), name="video"),
    url(r'^video/(?P<video_id>[0-9]+)/$',
        views.video_view, name="video"),
    url(r'^mark_video_watched/(?P<video_id>[0-9]+)/$',
        views.toggle_video_watched, name="toggle_video_watched")
]

auto_dict/templates/auto_dict/change_user_pic.html
<form action="{% url 'auto_dict:change_user_image' %}"  enctype="multipart/form-data" method="post">
  {% csrf_token %}
  {{form}}
  <input type="submit" value="Submit" name="Submit">
</form>

auto_dict/templates/auto_dict/chart.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
      <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Free Bootstrap Admin Template : Binary Admin</title>
	<!-- BOOTSTRAP STYLES-->
    <link href="assets/css/bootstrap.css" rel="stylesheet" />
     <!-- FONTAWESOME STYLES-->
    <link href="assets/css/font-awesome.css" rel="stylesheet" />
     <!-- MORRIS CHART STYLES-->
    <link href="assets/js/morris/morris-0.4.3.min.css" rel="stylesheet" />
        <!-- CUSTOM STYLES-->
    <link href="assets/css/custom.css" rel="stylesheet" />
     <!-- GOOGLE FONTS-->
   <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Binary admin</a> 
            </div>
  <div style="color: white;
padding: 15px 50px 5px 50px;
float: right;
font-size: 16px;"> Last access : 30 May 2014 &nbsp; <a href="#" class="btn btn-danger square-btn-adjust">Logout</a> </div>
        </nav>   
           <!-- /. NAV TOP  -->
                <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
				<li class="text-center">
                    <img src="assets/img/find_user.png" class="user-image img-responsive"/>
					</li>
				
					
                    <li>
                        <a href="index.html"><i class="fa fa-dashboard fa-3x"></i> Dashboard</a>
                    </li>
                    <li>
                        <a  href="ui.html"><i class="fa fa-desktop fa-3x"></i> UI Elements</a>
                    </li>
                    <li>
                        <a  href="tab-panel.html"><i class="fa fa-qrcode fa-3x"></i> Tabs & Panels</a>
                    </li>
						   <li  >
                        <a class="active-menu"   href="chart.html"><i class="fa fa-bar-chart-o fa-3x"></i> Morris Charts</a>
                    </li>	
                      <li  >
                        <a  href="table.html"><i class="fa fa-table fa-3x"></i> Table Examples</a>
                    </li>
                    <li  >
                        <a  href="form.html"><i class="fa fa-edit fa-3x"></i> Forms </a>
                    </li>				
					
					                   
                    <li>
                        <a href="#"><i class="fa fa-sitemap fa-3x"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="#">Second Level Link</a>
                            </li>
                            <li>
                                <a href="#">Second Level Link</a>
                            </li>
                            <li>
                                <a href="#">Second Level Link<span class="fa arrow"></span></a>
                                <ul class="nav nav-third-level">
                                    <li>
                                        <a href="#">Third Level Link</a>
                                    </li>
                                    <li>
                                        <a href="#">Third Level Link</a>
                                    </li>
                                    <li>
                                        <a href="#">Third Level Link</a>
                                    </li>

                                </ul>
                               
                            </li>
                        </ul>
                      </li>  
                  <li  >
                        <a  href="blank.html"><i class="fa fa-square-o fa-3x"></i> Blank Page</a>
                    </li>	
                </ul>
               
            </div>
            
        </nav>  
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper" >
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                     <h2>Morris Charts</h2>   
                        <h5>Welcome Jhon Deo , Love to see you back. </h5>
                       
                    </div>
                </div>
                 <!-- /. ROW  -->
                 <hr />
             
                <div class="row"> 
                    
                      
                               <div class="col-md-6 col-sm-12 col-xs-12">                     
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Bar Chart Example
                        </div>
                        <div class="panel-body">
                            <div id="morris-bar-chart"></div>
                        </div>
                    </div>            
                </div>
                      <div class="col-md-6 col-sm-12 col-xs-12">                     
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Area Chart Example
                        </div>
                        <div class="panel-body">
                            <div id="morris-area-chart"></div>
                        </div>
                    </div>            
                </div> 
                
           </div>
                 <!-- /. ROW  -->
                <div class="row">                     
                      
                               <div class="col-md-6 col-sm-12 col-xs-12">                     
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Donut Chart Example
                        </div>
                        <div class="panel-body">
                            <div id="morris-donut-chart"></div>
                        </div>
                    </div>            
                </div>
                      <div class="col-md-6 col-sm-12 col-xs-12">                     
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Line Chart Example
                        </div>
                        <div class="panel-body">
                            <div id="morris-line-chart"></div>
                        </div>
                    </div>            
                </div> 
                
           </div>
                 <!-- /. ROW  -->
    </div>
             <!-- /. PAGE INNER  -->
            </div>
         <!-- /. PAGE WRAPPER  -->
        </div>
     <!-- /. WRAPPER  -->
    <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
    <!-- JQUERY SCRIPTS -->
    <script src="assets/js/jquery-1.10.2.js"></script>
      <!-- BOOTSTRAP SCRIPTS -->
    <script src="assets/js/bootstrap.min.js"></script>
    <!-- METISMENU SCRIPTS -->
    <script src="assets/js/jquery.metisMenu.js"></script>
     <!-- MORRIS CHART SCRIPTS -->
     <script src="assets/js/morris/raphael-2.1.0.min.js"></script>
    <script src="assets/js/morris/morris.js"></script>
      <!-- CUSTOM SCRIPTS -->
    <script src="assets/js/custom.js"></script>
    
   
</body>
</html>

auto_dict/templates/auto_dict/login.html
{% load widget_tweaks %}
<form action="{% url 'auto_dict:login' %}" method="post">
	    	{% csrf_token %}
		    {{ form.username|attr:"placeholder:Username"  }}
		    {{ form.password|attr:"placeholder:Password"  }}
		    <br/>
		    <!-- <input type="submit" value="Register" name="Submit" class="submit" id="submit" > -->
		    <button type="submit">Sign In</button>
		    <br/>

		    <a class="input message error alignCenter" href="">Don't have an account? Register</a>
		  
</form>

auto_dict/templates/auto_dict/old_index.html
<!DOCTYPE html>
<html>
<head>
	<title>Search a Word!</title>
</head>
<body>
 <form action="{% url 'auto_dict:index' %}" method="post"> 
 	{% csrf_token %}
 	<input type="text" name="word" id="info">
 	<input type="submit" name="">
 </form>
 {{ word}}
 {{ definition }}
</body %>
</html>

auto_dict/templates/auto_dict/register.html
{% load widget_tweaks %}
<form action="{% url 'auto_dict:register' %}" method="post">
    {% csrf_token %}
    {{ form.username|attr:"placeholder:Username"  }}
    {{ form.email|attr:"placeholder:Email"  }}
    {{ form.password|attr:"placeholder:Password"  }}
    <br/>
    <!-- <input type="submit" value="Register" name="Submit" class="submit" id="submit" > -->
    <button type="submit">Register</button>
    <br/>

    <a class="input message error alignCenter" href="{% url 'auto_dict:login' %}">Already have an account? Login</a>
          
</form>

auto_dict/templates/auto_dict/video_detail.html
<video width="320" height="240" controls>
	<source src="{{video.file.url}}" type="video/mp4">
	<source src="{{video.file.url}}" type="video/webm">
	Your browser does not support the video tag.
</video>
<br>

auto_dict/templates/auto_dict/word_search.html
{% extends 'auto_dict/base.html' %}
{% load static %}
{% block title %}Word Search{% endblock %}
{% block page-wrapper %}


        <div id="page-wrapper" >
          <div id="page-inner">
              <div class="row">
                  <div class="col-md-12">
                   <h2>Word Search</h2>   
                      <h5>Please search your word below.</h5>
                        <form enctype="multipart/form-data" action="{% url 'auto_dict:word_search' %}" method="post"> 
                          {% csrf_token %}
                          <input type="text" name="word" id="info">
                          <h5>Or, upload a text file with comma-deleniated words.</h5>
                          <input type="file" name="file" id="info">
                          <input type="submit" placeholder="Search" name="Search">
                        </form>
                        

<!--                         <form enctype="multipart/form-data" action="/textfile_word_search/" method="post">
                          {% csrf_token %}
                          <input type="file" name="file" id="info">
                          <input type="submit" value="Save" />
                        </form> -->

                       {% if found_words %}
                         {% for word in found_words %}
                          <div class="panel panel-default">
                              <div class="panel-heading">
                              {{word.word}}
                              </div>
                              <div class="panel-body">
                                  <ul class="nav nav-pills">
                                      <li class="active"><a href="#definition{{word.id}}" data-toggle="tab">Definition</a>
                                      </li>
                                      <li class=""><a href="#example{{word.id}}" data-toggle="tab">Example</a>
                                      </li>
                                      <li class=""><a href="#origin{{word.id}}" data-toggle="tab">Origin</a>
                                      </li>
                                      <li class=""><a href="#full_json_response{{word.id}}" data-toggle="tab">Full JSON Response</a>
                                      </li>
                                      <li class=""><a href="#syllables{{word.id}}" data-toggle="tab">Syllables</a>
                                      </li>
                                      <li class=""><a href="#part_of_speech{{word.id}}" data-toggle="tab">Part of Speech</a>
                                      </li>
                                      <li class=""><a href="#pronunciation{{word.id}}" data-toggle="tab">Phonetic Prounciation</a>
                                      </li>
                                  </ul>

                                  <div class="tab-content">
                                      <div class="tab-pane fade active in" id="definition{{word.id}}">
                                          <h4>Definition: {{word.word}}</h4>
                                          <p>{{word.definition}}</p>
                                      </div>
                                      <div class="tab-pane fade" id="example{{word.id}}">
                                          <h4>Example: {{word.word}}</h4>
                                          <p>{{word.example}}</p>
                                      </div>
                                      <div class="tab-pane fade" id="origin{{word.id}}">
                                          <h4>Origin: {{word.word}}</h4>
                                          <p>{{word.origin}}</p>
                                      </div>
                                      <div class="tab-pane fade" id="full_json_response{{word.id}}">
                                          <h4>Full Json Response: {{word.word}}</h4>
                                          <p>{{word.full_json_response}}</p>
                                      </div>
                                      <div class="tab-pane fade" id="syllables{{word.id}}">
                                          <h4>Syllables: {{word.word}}</h4>
                                          <p>{{word.syllables}}</p>
                                      </div>
                                      <div class="tab-pane fade" id="part_of_speech{{word.id}}">
                                          <h4>Part of Speech: {{word.word}}</h4>
                                          <p>{{word.part_of_speech}}</p>
                                      </div>
                                      <div class="tab-pane fade" id="pronunciation{{word.id}}">
                                          <h4>Phonetic Pronunciation: {{word.word}}</h4>
                                          <p>{{word.pronunciation}}</p>
                                      </div>
                                  </div>
                              </div>
                          </div>
                          {% endfor %}
                        {% endif %}
                     
                  </div>
              </div>
                 <!-- /. ROW  -->
                 <hr />

          {% if words %}
          <div class="row">
              <div class="col-md-12">
                  <!-- Advanced Tables -->
                  <div class="panel panel-default">
                      <div class="panel-heading">
                           Words Database
                      </div>
                      <div class="panel-body">
                          <div class="table-responsive">
                              <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                  <thead>
                                      <tr>
                                          <th>Word</th>
                                          <th>Definition</th>
                                          <th>Part of Speech(s)</th>
                                          <th>Other Usages</th>
                                          <th>Origin</th>
                                      </tr>
                                  </thead>
                                  {% for word in words %}
                                  <tbody>
                                      <tr class="odd gradeX">
                                          <td>{{word.word}}</td>
                                          <td>{{word.definition}}</td>
                                          <td>{{word.part_of_speech}}</td>
                                          <td class="center">{{word.other_usages}}</td>
                                          <td class="center">{{word.origin}}</td>
                                      </tr>
                                  </tbody>
                                  {% endfor %}
                              </table>
                          </div>
                          
                      </div>
                  </div>
                  <!--End Advanced Tables -->
              </div>
          </div>
              <!-- /. ROW  -->
          {% endif %}
               
    </div>
             <!-- /. PAGE INNER  -->
            </div>
         <!-- /. PAGE WRAPPER  -->
         
{% endblock page-wrapper %}